[package]

name = "piston_window"
version = "0.71.1"
authors = ["bvssvni <bvssvni@gmail.com>"]
keywords = ["window", "piston"]
description = "The official Piston window wrapper for the Piston game engine"
license = "MIT"
readme = "README.md"
repository = "https://github.com/pistondevelopers/piston_window.git"
homepage = "https://github.com/pistondevelopers/piston_window"
documentation = "https://docs.rs/piston_window"

[lib]

path = "src/lib.rs"
name = "piston_window"


[dependencies]
gfx = "0.16.0"
gfx_device_gl = "0.14.0"
piston = "0.34.0"
piston2d-gfx_graphics = "0.44.0"
piston2d-graphics = "0.22.0"
piston-texture = "0.5.0"
shader_version = "0.3.0"
pistoncore-glutin_window = "0.40.0"
