[package]

name = "piston_window"
version = "0.0.5"
authors = ["bvssvni <bvssvni@gmail.com>"]
keywords = ["window", "piston"]
description = "The official Piston window back-end for the Piston game engine"
license = "MIT"
readme = "README.md"
repository = "https://github.com/pistondevelopers/piston_window.git"
homepage = "https://github.com/pistondevelopers/piston_window"

[lib]

path = "src/lib.rs"
name = "piston_window"

[dependencies.piston]
git = "https://github.com/pistondevelopers/piston"

[dependencies.gfx]
git = "https://github.com/gfx-rs/gfx-rs"

[dependencies.gfx_device_gl]
git = "https://github.com/gfx-rs/gfx_device_gl"

[dependencies.piston2d-gfx_graphics]
git = "https://github.com/pistondevelopers/gfx_graphics"

[dependencies.piston2d-graphics]
git = "https://github.com/pistondevelopers/graphics"

[dev-dependencies.pistoncore-glutin_window]
git = "https://github.com/pistondevelopers/glutin_window"
