[package]

name = "piston_window"
version = "0.36.2"
authors = ["bvssvni <bvssvni@gmail.com>"]
keywords = ["window", "piston"]
description = "The official Piston window wrapper for the Piston game engine"
license = "MIT"
readme = "README.md"
repository = "https://github.com/pistondevelopers/piston_window.git"
homepage = "https://github.com/pistondevelopers/piston_window"

[lib]

path = "src/lib.rs"
name = "piston_window"


[dependencies]
gfx = "0.9.0"
gfx_device_gl = "0.8.0"
piston = "0.18.0"
piston2d-gfx_graphics = "0.20.0"
piston2d-graphics = "0.14.0"
shader_version = "0.2.0"
pistoncore-glutin_window = "0.21.0"
