[package]

name = "piston_window"
version = "0.31.0"
authors = ["bvssvni <bvssvni@gmail.com>"]
keywords = ["window", "piston"]
description = "The official Piston window back-end for the Piston game engine"
license = "MIT"
readme = "README.md"
repository = "https://github.com/pistondevelopers/piston_window.git"
homepage = "https://github.com/pistondevelopers/piston_window"

[lib]

path = "src/lib.rs"
name = "piston_window"


[dependencies]
gfx = "0.8.1"
gfx_device_gl = "0.7.0"
piston = "0.16.0"
piston2d-gfx_graphics = "0.15.0"
piston2d-graphics = "0.11.0"
shader_version = "0.2.0"
pistoncore-glutin_window = "0.19.0"
